### PR TITLE
Multifield

### PR DESCRIPTION
**Pull request by brennhill**
From my team around allowing multifield and composite fields.

### CODE REVIEW

**Comment by michaelhodgdon** [comment]
This appears to be duplicating the functionality of the DialogFieldSet that is already in place.  Is that not meeting your use case?

**Comment by brennhill** [comment]
Our understanding was that the DialogFieldSet created a set of fields, this is more about creating dialogs from nested subclasses and having those get pulled into the final dialog.  Was our understanding incorrect?  We didn't find docs specifying exactly what DialogFieldSet does/is meant to do.

**Comment by michaelhodgdon** [comment]
DialogFieldSet creates a set of fields using a nested class.  You can also extend other classes to add fields from them (http://code.digitalatolson.com/cq-component-maven-plugin/usage.html#/Inheritance)

**Comment by brennhill** [comment]
ok,  we'll cancel it.  Thanks for the explanation.

**Pull request closed without merging**
