### PR TITLE
Provide Configurable Package Name

### PR DESCRIPTION
**Pull request by christopher-w-leggett**
Looking to add ability to specify package names.

### CODE REVIEW

**Comment by michaelhodgdon** [comment]
Chris, what is the use case for configuring the temp package name?  Can't we just derive that from the configured package name?

**Comment by christopher-w-leggett** [comment]
We can derive it from the configured package name.  I don't have a use case for making it fully configurable.  I'll work on making the change.

**Comment by christopher-w-leggett** [comment]
Updated.  Let me know if you have any concerns.

**Comment by michaelhodgdon** [comment]
That checking for the zip ending bit made me wonder, why are we including that in the package filename?  Shouldn't we just have the file name and add zip ourselves (so the default would be ${project.build.directory}/${project.build.finalName} and we'd add the extension when we need to).  There isn't a use case where this isn't a zip.

**Comment by christopher-w-leggett** [comment]
That makes sense.  I made the appropriate changes.

**Comment by michaelhodgdon** [comment]
One last thing, why is the build directory part of the file name configuration?

**Comment by christopher-w-leggett** [comment]
I modeled it after other plugins (ex. aem-package-maven-plugin) for consistency, but we are slowly moving in another direction (extension removal).  I don't see any reason why it would be required.

**Comment by michaelhodgdon** [comment]
Yeah I don't think it should be.  All artifacts should be in the build directory.  This should be the last change and I'll merge it in.

**Comment by christopher-w-leggett** [comment]
Build directory has been removed from the configuration.

**Pull request merged**
